
services:
    vs-tutor:
        env_file:
            - .env
        build:
            context: .
        environment:
            NODE_ENV: production
        ports:
            - 8501:8501
        restart: on-failure
        volumes:
            - user_data:/data

volumes:
    user_data:
